# Generated by Django 3.2.11 on 2022-01-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proyecto', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True)),
                ('titulo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appToDo.proyecto')),
            ],
        ),
    ]
