# Generated by Django 3.2.11 on 2022-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
