# Generated by Django 3.2.11 on 2022-02-06 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appToDo', '0009_alter_proyecto_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
