# Generated by Django 3.2.11 on 2022-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0010_tarea_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange'), ('gray', 'gray')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
