# Generated by Django 3.2.11 on 2022-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0013_alter_proyecto_titulo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='titulo_proyecto',
            field=models.CharField(max_length=20),
        ),
    ]
