# Generated by Django 3.2.11 on 2022-02-11 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appToDo', '0014_alter_proyecto_titulo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
